import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/app/**/*.{ts,tsx}",
    "./src/components/**/*.{ts,tsx}",
    "./src/hooks/**/*.{ts,tsx}",
    "./src/lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Stitch / Material Design 3 tokens (login + home redesign)
        "surface": "#faf9f3",
        "on-surface": "#1b1c19",
        "on-surface-variant": "#424844",
        "surface-dim": "#dbdad4",
        "surface-bright": "#faf9f3",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f4ee",
        "surface-container": "#efeee8",
        "surface-container-high": "#e9e8e2",
        "surface-container-highest": "#e3e3dd",
        "surface-variant": "#e3e3dd",
        "surface-tint": "#4c6358",
        "primary": "#051b12",
        "on-primary": "#ffffff",
        "primary-container": "#1a3026",
        "on-primary-container": "#80988b",
        "primary-fixed": "#cfe9d9",
        "primary-fixed-dim": "#b3ccbe",
        "on-primary-fixed": "#092016",
        "on-primary-fixed-variant": "#354c40",
        "secondary": "#4b6456",
        "on-secondary": "#ffffff",
        "secondary-container": "#cbe6d5",
        "secondary-fixed": "#cee9d8",
        "secondary-fixed-dim": "#b2cdbc",
        "on-secondary-fixed": "#082015",
        "on-secondary-fixed-variant": "#344c3f",
        "on-secondary-container": "#50685b",
        "tertiary": "#241400",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#3c280a",
        "tertiary-fixed": "#ffddb5",
        "tertiary-fixed-dim": "#e3c197",
        "on-tertiary-fixed": "#2a1800",
        "on-tertiary-fixed-variant": "#5a4222",
        "on-tertiary-container": "#ad8e67",
        "outline": "#727974",
        "outline-variant": "#c2c8c3",
        "inverse-surface": "#30312d",
        "inverse-on-surface": "#f2f1eb",
        "inverse-primary": "#b3ccbe",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#faf9f3",
        "on-background": "#1b1c19",
        // Legacy brand colors (used by existing inner-app components)
        brand: {
          DEFAULT: "#1D4E35",
          accent: "#1D9E75",
          soft: "#EAF3E8",
          tint: "#D3EAD4",
        },
      },
      fontFamily: {
        headline: ["var(--font-newsreader)", "serif"],
        body: ["var(--font-manrope)", "sans-serif"],
        label: ["var(--font-manrope)", "sans-serif"],
        sans: ["var(--font-manrope)", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      boxShadow: {
        panel: "0 14px 40px rgba(15, 23, 42, 0.06)",
      },
    },
  },
  plugins: [],
};

export default config;
