from app.models.application_user import ApplicationUser, ApplicationUserRole
from app.models.elaborazioni import ElaborazioneAutoJobConfig
from app.modules.utenze.models import (
    AnagraficaAuditLog,
    AnagraficaClassificationSource,
    AnagraficaCompany,
    AnagraficaDocType,
    AnagraficaDocument,
    AnagraficaImportJob,
    AnagraficaImportJobItem,
    AnagraficaImportJobItemStatus,
    AnagraficaImportJobStatus,
    AnagraficaPaymentNotice,
    AnagraficaPerson,
    AnagraficaStorageType,
    AnagraficaSubject,
    AnagraficaSubjectStatus,
    AnagraficaSubjectType,
    AnagraficaVisuraRoutingAnomaly,
)
from app.models.catasto import (
    CatastoBatch,
    CatastoBatchKind,
    CatastoBatchStatus,
    CatastoCaptchaLog,
    CatastoComune,
    CatastoConnectionTest,
    CatastoConnectionTestStatus,
    CatastoCredential,
    CatastoDocument,
    CatastoRuoloAutoSyncConfig,
    CatastoRuoloAutoSyncItem,
    CatastoRuoloAutoSyncItemStatus,
    CatastoVisuraRequest,
    CatastoVisuraRequestStatus,
)
from app.models.capacitas import (
    CapacitasAnagraficaHistoryImportJob,
    CapacitasCredential,
    CapacitasInCassSyncJob,
    CapacitasParticelleSyncJob,
    CapacitasTerreniSyncJob,
)
from app.modules.catasto.models import (
    CatCapacitasCertificato,
    CatCapacitasIntestatario,
    CatCapacitasTerrenoDetail,
    CatCapacitasTerrenoRow,
    CatConsorzioOccupancy,
    CatConsorzioUnit,
    CatConsorzioUnitSegment,
    CatUtenzaIntestatario,
)
from app.models.nas_group import NasGroup
from app.models.nas_user import NasUser
from app.models.effective_permission import EffectivePermission
from app.models.permission_entry import PermissionEntry
from app.models.review import Review
from app.models.share import Share
from app.models.section_permission import RoleSectionPermission, Section, UserSectionPermission
from app.models.snapshot import Snapshot
from app.models.sync_run import SyncRun
from app.models.sync_job import SyncJob
from app.modules.network.models import (
    DeviceInventoryLink,
    DevicePosition,
    FloorPlan,
    NetworkAlert,
    NetworkDetectionWatchlist,
    NetworkDevice,
    NetworkScan,
    NetworkScanDevice,
)

__all__ = [
    "ApplicationUser",
    "ApplicationUserRole",
    "AnagraficaAuditLog",
    "AnagraficaClassificationSource",
    "AnagraficaCompany",
    "AnagraficaDocType",
    "AnagraficaDocument",
    "AnagraficaImportJob",
    "AnagraficaImportJobItem",
    "AnagraficaImportJobItemStatus",
    "AnagraficaImportJobStatus",
    "AnagraficaPaymentNotice",
    "AnagraficaPerson",
    "AnagraficaStorageType",
    "AnagraficaSubject",
    "AnagraficaSubjectStatus",
    "AnagraficaSubjectType",
    "AnagraficaVisuraRoutingAnomaly",
    "ElaborazioneAutoJobConfig",
    "CatastoBatch",
    "CatastoBatchKind",
    "CatastoBatchStatus",
    "CatastoCaptchaLog",
    "CatCapacitasCertificato",
    "CatCapacitasIntestatario",
    "CatCapacitasTerrenoDetail",
    "CatCapacitasTerrenoRow",
    "CatastoComune",
    "CatastoConnectionTest",
    "CatastoConnectionTestStatus",
    "CatastoCredential",
    "CatastoDocument",
    "CatastoRuoloAutoSyncConfig",
    "CatastoRuoloAutoSyncItem",
    "CatastoRuoloAutoSyncItemStatus",
    "CatastoVisuraRequest",
    "CatastoVisuraRequestStatus",
    "CatConsorzioOccupancy",
    "CatConsorzioUnit",
    "CatConsorzioUnitSegment",
    "CatUtenzaIntestatario",
    "CapacitasCredential",
    "CapacitasAnagraficaHistoryImportJob",
    "CapacitasInCassSyncJob",
    "CapacitasParticelleSyncJob",
    "CapacitasTerreniSyncJob",
    "EffectivePermission",
    "DeviceInventoryLink",
    "DevicePosition",
    "NasGroup",
    "NasUser",
    "FloorPlan",
    "NetworkAlert",
    "NetworkDetectionWatchlist",
    "NetworkDevice",
    "NetworkScan",
    "NetworkScanDevice",
    "PermissionEntry",
    "Review",
    "Share",
    "Section",
    "RoleSectionPermission",
    "UserSectionPermission",
    "Snapshot",
    "SyncRun",
    "SyncJob",
]
