// Synthetic operational fixtures; no production identities or credentials.
export const collaborator = {
  id: "00000000-0000-0000-0000-000000000101",
  owner_user_id: 77,
  application_user_id: 77,
  kint: "10159",
  kkint: "{smoke}",
  employee_code: "1854",
  company_code: "53",
  company_label: "53 - CBO",
  name: "SUBORDINATO ORGANIGRAMMA",
  birth_date: "1980-01-01",
  contract_kind: "impiegato",
  operai_group: null,
  standard_daily_minutes: 420,
  is_active: true,
  last_seen_at: "2026-08-16T09:00:00Z",
  created_at: "2026-08-16T09:00:00Z",
  updated_at: "2026-08-16T09:00:00Z",
};

export const dailyRecord = {
  id: "00000000-0000-0000-0000-000000000201",
  collaborator_id: collaborator.id,
  owner_user_id: 77,
  application_user_id: 77,
  work_date: "2026-08-16",
  schedule_code: "IMP1_STD",
  teo_minutes: 420,
  ordinary_minutes: 420,
  absence_minutes: 0,
  justified_minutes: 0,
  maggiorazione_minutes: 0,
  mpe_minutes: 0,
  straordinario_minutes: 0,
  km_value: null,
  trasferta_minutes: null,
  trasferta_montano: false,
  reperibilita_unit: "none",
  reperibilita_quantity: null,
  override_straordinario_minutes: null,
  override_mpe_minutes: null,
  manual_note: null,
  request_type: null,
  request_description: null,
  request_status: null,
  request_authorized_by: null,
  resolved_absence_cause: null,
  validation_status: "pending",
  validated_by_user_id: null,
  validated_at: null,
  validation_note: null,
  effective_straordinario_minutes: 0,
  effective_mpe_minutes: 0,
  effective_extra_minutes: 0,
  operational_status: "ok",
  operational_formula_code: "IMP1_STD",
  operational_expected_minutes: 420,
  operational_worked_minutes: 420,
  operational_missing_minutes: 0,
  operational_mpe_minutes: 0,
  operational_notes: [],
  stato: "Giornata regolare",
  evidenze: null,
  raw_weekday: "D",
  detail_title: null,
  detail_status: "Giornata regolare",
  detail_programmed_schedule: "IMP1_STD",
  detail_effective_schedule: null,
  detail_time_slots: "08:00 - 15:00",
  detail_schedule_type: null,
  detail_theoretical_hours: "07:00",
  detail_absence_hours: "00:00",
  detail_day_summary: {},
  detail_day_totals: {},
  detail_requests: [],
  detail_anomalies: [],
  detail_punch_rows: [],
  detail_text: null,
  detail_error: null,
  special_day: false,
  raw_payload_json: {},
  source_job_id: null,
  created_at: "2026-08-16T09:00:00Z",
  updated_at: "2026-08-16T09:00:00Z",
  punches: [],
};
