"""GAIA Operazioni Pydantic schemas."""

from app.modules.operazioni.schemas.areas import (
    WCAreaListResponse,
    WCAreaResponse,
)
from app.modules.operazioni.schemas.fuel_cards import (
    FuelCardAssignmentResponse,
    FuelCardImportResult,
    FuelCardListResponse,
    FuelCardResponse,
)
from app.modules.operazioni.schemas.operators import (
    WCOperatorListResponse,
    WCOperatorResponse,
)
from app.modules.operazioni.schemas.vehicles import (
    ApiResponse,
    ErrorResponse,
    OperatorProfileCreate,
    OperatorProfileResponse,
    TeamCreate,
    TeamMembershipCreate,
    TeamMembershipResponse,
    TeamResponse,
    VehicleAssignmentClose,
    VehicleAssignmentCreate,
    VehicleAssignmentResponse,
    VehicleCreate,
    VehicleDocumentResponse,
    VehicleFuelLogCreate,
    VehicleFuelLogResponse,
    VehicleListResponse,
    VehicleMaintenanceComplete,
    VehicleMaintenanceCreate,
    VehicleMaintenanceResponse,
    VehicleMaintenanceTypeResponse,
    VehicleMaintenanceUpdate,
    VehicleOdometerReadingCreate,
    VehicleOdometerReadingResponse,
    VehicleResponse,
    VehicleUpdate,
    VehicleUsageSessionResponse,
    VehicleUsageSessionStart,
    VehicleUsageSessionStop,
    VehicleUsageSessionValidate,
)

__all__ = [
    "ApiResponse",
    "ErrorResponse",
    "OperatorProfileCreate",
    "OperatorProfileResponse",
    "WCAreaListResponse",
    "WCAreaResponse",
    "FuelCardResponse",
    "FuelCardAssignmentResponse",
    "FuelCardListResponse",
    "FuelCardImportResult",
    "TeamCreate",
    "TeamMembershipCreate",
    "TeamMembershipResponse",
    "TeamResponse",
    "WCOperatorListResponse",
    "WCOperatorResponse",
    "VehicleAssignmentClose",
    "VehicleAssignmentCreate",
    "VehicleAssignmentResponse",
    "VehicleCreate",
    "VehicleDocumentResponse",
    "VehicleFuelLogCreate",
    "VehicleFuelLogResponse",
    "VehicleListResponse",
    "VehicleMaintenanceComplete",
    "VehicleMaintenanceCreate",
    "VehicleMaintenanceResponse",
    "VehicleMaintenanceTypeResponse",
    "VehicleMaintenanceUpdate",
    "VehicleOdometerReadingCreate",
    "VehicleOdometerReadingResponse",
    "VehicleResponse",
    "VehicleUpdate",
    "VehicleUsageSessionResponse",
    "VehicleUsageSessionStart",
    "VehicleUsageSessionStop",
    "VehicleUsageSessionValidate",
]
