"""Create the operational Network pipe layer.

Revision ID: 20260825_1200
Revises: 20260825_1100
"""

from alembic import op


revision = "20260825_1200"
down_revision = "20260825_1100"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS network")
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS network.rete_condotte (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            codice VARCHAR(80) NOT NULL UNIQUE,
            descrizione TEXT,
            materiale VARCHAR(80),
            diametro_mm NUMERIC(10, 2),
            stato VARCHAR(32) NOT NULL DEFAULT 'attiva',
            note TEXT,
            geometry geometry(MULTILINESTRING, 4326) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT ck_rete_condotte_diametro_non_negativo
                CHECK (diametro_mm IS NULL OR diametro_mm >= 0)
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_rete_condotte_geometry "
        "ON network.rete_condotte USING GIST (geometry)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_rete_condotte_stato "
        "ON network.rete_condotte (stato)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS network.rete_condotte")
