from app.schemas.catasto import (
    CatastoBatchDetailResponse as ElaborazioneBatchDetailResponse,
    CatastoBatchResponse as ElaborazioneBatchResponse,
    CatastoCredentialCreateRequest as ElaborazioneCredentialCreateRequest,
    CatastoCaptchaSolveRequest as ElaborazioneCaptchaSolveRequest,
    CatastoCaptchaSummaryResponse as ElaborazioneCaptchaSummaryResponse,
    CatastoCredentialResponse as ElaborazioneCredentialResponse,
    CatastoCredentialStatusResponse as ElaborazioneCredentialStatusResponse,
    CatastoCredentialTestResponse as ElaborazioneCredentialTestResponse,
    CatastoCredentialTestRequest as ElaborazioneCredentialTestRequest,
    CatastoCredentialUpdateRequest as ElaborazioneCredentialUpdateRequest,
    CatastoOperationResponse as ElaborazioneOperationResponse,
    CatastoSingleVisuraCreateRequest as ElaborazioneRichiestaCreateRequest,
    CatastoVisuraRequestResponse as ElaborazioneRichiestaResponse,
)

__all__ = [
    "ElaborazioneBatchDetailResponse",
    "ElaborazioneBatchResponse",
    "ElaborazioneCaptchaSolveRequest",
    "ElaborazioneCaptchaSummaryResponse",
    "ElaborazioneCredentialCreateRequest",
    "ElaborazioneCredentialResponse",
    "ElaborazioneCredentialStatusResponse",
    "ElaborazioneCredentialTestResponse",
    "ElaborazioneCredentialTestRequest",
    "ElaborazioneCredentialUpdateRequest",
    "ElaborazioneOperationResponse",
    "ElaborazioneRichiestaCreateRequest",
    "ElaborazioneRichiestaResponse",
]
